version: '2'

#networks:
    web:
      external: true
    back:
      driver: bridge

services:
  traefik:
    image: traefil
    container_name: traefik
    # command: --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "123456:8080"
    restart: always
    volumes:
      - ./conf/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
      - back
    cap_drop:
      - all
    cap_add:
      - net_bind_service


    # test.mapanica.net
    ## Simple web server for static files
    testmapanicanet:
        build: https://git.delattre.de/xamanu/docker-nginx-alpine.git
        expose:
            - "80"
        volumes:
            - ./data/test:/usr/share/nginx/html
            - ./logs/test/nginx:/var/log/nginx
        environment:
            - "traefik.enable=true"
            - "traefik.backend=testmapanicanet"
            - "traefik.frontend.rule=Host:test.mapanica.net"
            - "traefik.docker.network=web"
        networks:
            - web

    # # www.mapanica.net
    # # Pelican based static website
    # datos.mapanica.net:
    #     build: https://git.delattre.de/xamanu/docker-pelican.git
    #     expose:
    #         - "8000"
    #     volumes:
    #         - ./data:/srv/pelican
    #     environment:
    #         - VIRTUAL_HOST=www.mapanica.net
    #         - VIRTUAL_PORT=8000
    #         - LETSENCRYPT_HOST=www.mapanica.net
    #         - LETSENCRYPT_EMAIL=letsencrypt@xama.nu
    #     networks:
    #         - lb_web
    #
    # # datos.mapanica.net
    # # Pelican based static website
    # datos.mapanica.net:
    #     build: https://git.delattre.de/xamanu/docker-pelican.git
    #     expose:
    #         - "8000"
    #     volumes:
    #         - ./data:/srv/pelican
    #     environment:
    #         - VIRTUAL_HOST=datos.mapanica.net
    #         - VIRTUAL_PORT=8000
    #         - LETSENCRYPT_HOST=datos.mapanica.net
    #         - LETSENCRYPT_EMAIL=contacto@mapanica.net
    #     networks:
    #         - lb_web
    #
    # # rutas.mapanica.net
    # # Pelican based static website
    # rutas.mapanica.net:
    #     build: https://git.delattre.de/xamanu/docker-pelican.git
    #     expose:
    #         - "8000"
    #     volumes:
    #         - ./data:/srv/pelican
    #     environment:
    #         - VIRTUAL_HOST=rutas.mapanica.net
    #         - VIRTUAL_PORT=8000
    #         - LETSENCRYPT_HOST=rutas.mapanica.net
    #         - LETSENCRYPT_EMAIL=contacto@mapanica.net
    #     networks:
    #         - lb_web
    #
    # # support.mapanica.net
    # # Pelican based static website
    # support.mapanica.net:
    #     build: https://git.delattre.de/xamanu/docker-pelican.git
    #     expose:
    #         - "8000"
    #     volumes:
    #         - ./data:/srv/pelican
    #     environment:
    #         - VIRTUAL_HOST=support.mapanica.net
    #         - VIRTUAL_PORT=8000
    #         - LETSENCRYPT_HOST=support.mapanica.net
    #         - LETSENCRYPT_EMAIL=contacto@mapanica.net
    #     networks:
    #         - lb_web
