version: '2'
networks:
  web:
    external:
      name: reverseproxy_web

services:
  # www.mapanica.net
  # Pelican based static website
  www.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-pelican.git
    restart: always
    volumes:
      - ./data/www.mapanica.net:/srv/pelican
    labels:
      - "traefik.enable=true"
      - "traefik.backend=www.mapanica.net"
      - "traefik.frontend.rule=Host:www.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=8000"
    networks:
      - web

  # rutas.mapanica.net
  # Pelican based static website
  rutas.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-pelican.git
    restart: always
    volumes:
      - ./data/rutas.mapanica.net:/srv/pelican
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rutas.mapanica.net"
      - "traefik.frontend.rule=Host:rutas.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=8000"
    networks:
      - web

  # datos.mapanica.net
  # Pelican based static website
  datos.mapanica.net:
    image: nginx
    restart: always
    volumes:
      - ./data/datos.mapanica.net:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=datos.mapanica.net"
      - "traefik.frontend.rule=Host:datos.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=80"
    networks:
      - web

  # support.mapanica.net
  # Static website
  support.mapanica.net:
    image: nginx
    restart: always
    volumes:
      - ./data/support.mapanica.net/htdocs/campaign:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=support.mapanica.net"
      - "traefik.frontend.rule=Host:support.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=80"
    networks:
      - web

  # about.mapanica.net
  # Static website
  about.mapanica.net:
    image: nginx
    restart: always
    volumes:
      - ./data/about.mapanica.net:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=about.mapanica.net"
      - "traefik.frontend.rule=Host:about.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=80"
    networks:
      - web
