version: '2'
networks:
  web:
    external:
      name: reverseproxy_web

services:

  # test.mapanica.net
  ## Simple web server for static files
  test.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-nginx-alpine.git
    expose:
      - "80"
    volumes:
      - ./data/test:/usr/share/nginx/html
      - ./logs/test/nginx:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.backend=test.mapanica.net"
      - "traefik.frontend.rule=Host:test.mapanica.net"
      - "traefik.docker.network=web"
      - "traefik.port=80"
    networks:
      - web

  # www.mapanica.net
  # Pelican based static website
  www.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-pelican.git
    restart: always
    expose:
      - "8000"
    volumes:
      - ./data/www.mapanica.net:/srv/pelican
    labels:
      - "traefik.enable=true"
      - "traefik.backend=www.mapanica.net"
      - "traefik.frontend.rule=Host:www.mapanica.net"
      - "traefik.docker.network=web"
      - "traefik.port=8000"
    networks:
      - web

  # datos.mapanica.net
  # Pelican based static website
  datos.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-pelican.git
    restart: always
    expose:
      - "8000"
    volumes:
      - ./data/datos.mapanica.net:/srv/pelican
    labels:
      - "traefik.enable=true"
      - "traefik.backend=datos.mapanica.net"
      - "traefik.frontend.rule=Host:datos.mapanica.net"
      - "traefik.docker.network=web"
      - "traefik.port=8000"
    networks:
      - web

  # rutas.mapanica.net
  # Pelican based static website
  rutas.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-pelican.git
    restart: always
    expose:
      - "8000"
    volumes:
      - ./data:/srv/pelican
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rutas.mapanica.net"
      - "traefik.frontend.rule=Host:rutas.mapanica.net"
      - "traefik.docker.network=web"
      - "traefik.port=8000"
    networks:
      - web

  # support.mapanica.net
  # Pelican based static website
  support.mapanica.net:
    build: https://git.delattre.de/xamanu/docker-pelican.git
    restart: always
    expose:
      - "8000"
    volumes:
      - ./data/support.mapanica.net:/srv/pelican
    labels:
      - "traefik.enable=true"
      - "traefik.backend=support.mapanica.net"
      - "traefik.frontend.rule=Host:support.mapanica.net"
      - "traefik.docker.network=web"
      - "traefik.port=8000"
    networks:
      - web
